#!/usr/bin/env python3
# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Render the repository-owned security architecture as a deterministic SVG."""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import sys
from pathlib import Path

for _p in (Path(__file__).resolve(), *Path(__file__).resolve().parents):
    if (_p / "scripts" / "_bootstrap.py").exists():
        sys.path.insert(0, str(_p / "scripts"))
        break
from _bootstrap import find_repo_root  # noqa: E402

ROOT = find_repo_root(Path(__file__).resolve())
MODEL = ROOT / "docs" / "security-architecture.json"
OUTPUT = ROOT / "docs" / "security-architecture.svg"
COURSE_SCOPED_TITLE = "Security architecture for the DLI course Securing Agents with OpenShell and NemoClaw"


def canonical_bytes(model: dict) -> bytes:
    return (json.dumps(model, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n").encode()


def model_digest(model: dict) -> str:
    return hashlib.sha256(canonical_bytes(model)).hexdigest()


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def wrap(text: str, limit: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if current and len(candidate) > limit:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return lines or [""]


def text_block(x: float, y: float, lines: list[str], css: str, *, anchor: str = "middle", step: int = 18) -> str:
    tspans = []
    for index, line in enumerate(lines):
        dy = "0" if index == 0 else str(step)
        tspans.append(f'<tspan x="{x:g}" dy="{dy}">{esc(line)}</tspan>')
    return f'<text x="{x:g}" y="{y:g}" text-anchor="{anchor}" class="{css}">' + "".join(tspans) + "</text>"


def anchor(node: dict, target: dict) -> tuple[float, float]:
    cx = node["x"] + node["width"] / 2
    cy = node["y"] + node["height"] / 2
    tx = target["x"] + target["width"] / 2
    ty = target["y"] + target["height"] / 2
    dx, dy = tx - cx, ty - cy
    if abs(dx) >= abs(dy):
        return (node["x"] + node["width"] if dx >= 0 else node["x"], cy)
    return (cx, node["y"] + node["height"] if dy >= 0 else node["y"])


def side_anchor(node: dict, side: str | None, target: dict, fraction: float | None = None) -> tuple[float, float]:
    if not side:
        return anchor(node, target)
    fraction = 0.5 if fraction is None else fraction
    cx = node["x"] + node["width"] * fraction
    cy = node["y"] + node["height"] * fraction
    return {
        "top": (cx, node["y"]),
        "right": (node["x"] + node["width"], cy),
        "bottom": (cx, node["y"] + node["height"]),
        "left": (node["x"], cy),
    }[side]


def edge_path(source: dict, target: dict, route: dict | None = None) -> tuple[str, float, float]:
    route = route or {}
    x1, y1 = tuple(route["from_point"]) if route.get("from_point") else side_anchor(source, route.get("from_side"), target, route.get("from_fraction"))
    x2, y2 = tuple(route["to_point"]) if route.get("to_point") else side_anchor(target, route.get("to_side"), source, route.get("to_fraction"))
    via = [tuple(point) for point in route.get("via", [])]
    if via:
        points = [(x1, y1), *via, (x2, y2)]
        badge_index = max(0, (len(points) - 2) // 2)
        ax, ay = points[badge_index]
        bx, by = points[badge_index + 1]
        badge_x, badge_y = tuple(route.get("badge_point", ((ax + bx) / 2, (ay + by) / 2)))
        return " ".join(f"{x:g},{y:g}" for x, y in points), badge_x, badge_y
    if abs(x2 - x1) >= abs(y2 - y1):
        mid = (x1 + x2) / 2
        points = [(x1, y1), (mid, y1), (mid, y2), (x2, y2)]
    else:
        mid = (y1 + y2) / 2
        points = [(x1, y1), (x1, mid), (x2, mid), (x2, y2)]
    return " ".join(f"{x:g},{y:g}" for x, y in points), (x1 + x2) / 2, (y1 + y2) / 2


def render(model: dict) -> str:
    width = int(model["canvas"]["width"])
    height = int(model["canvas"]["height"])
    digest = model_digest(model)
    nodes = {node["id"]: node for node in model["nodes"]}
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<!-- generated by scripts/figures/render_security_architecture.py; model-sha256:{digest} -->',
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc" data-architecture-schema="{esc(model["schema"])}">',
        f'<title id="title">{esc(COURSE_SCOPED_TITLE)}</title>',
        '<desc id="desc">The Target of Evaluation is course source and CI definitions, the static artifact, and course client code. Hosting, CI execution, the browser environment, model services, runtime services, and relays are external dependencies whose live controls are not attested here. Threat enumeration is limited to the numbered flows and their listed security objectives. External operator internals are excluded.</desc>',
        """<defs>
  <marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L0,6 L9,3 z" fill="context-stroke"/></marker>
  <filter id="shadow" x="-10%" y="-10%" width="120%" height="130%"><feDropShadow dx="0" dy="3" stdDeviation="4" flood-opacity=".18"/></filter>
</defs>
<style>
  .bg{fill:#f7f8fa}.title{font:700 28px system-ui,sans-serif;fill:#111827}.subtitle{font:15px system-ui,sans-serif;fill:#4b5563}
  .zone{stroke-width:2;rx:18}.zone.supply{fill:#eef5e7;stroke:#76a900}.zone.external{fill:#f5f3ff;stroke:#7c65b5}.zone.gateway{fill:#eef6ff;stroke:#3979ad}.zone.internal{fill:#edf8f1;stroke:#37805a}.zone.host{fill:#fff4e8;stroke:#bf6b24}
  .zone-label{font:700 15px system-ui,sans-serif;letter-spacing:.4px;fill:#263238}.node{fill:#fff;stroke:#4b5563;stroke-width:2;rx:12;filter:url(#shadow)}
  .node.toe{stroke:#4a7a00;stroke-width:3}.node.external-context{fill:#fafafa;stroke:#6b7280;stroke-dasharray:8 6;filter:none}.node.privileged{stroke:#c45a18;stroke-width:3}.node.conditional{stroke-dasharray:8 6}.node-label{font:700 16px system-ui,sans-serif;fill:#111827}.node-detail{font:13px system-ui,sans-serif;fill:#4b5563}
  .ownership-toe{font:700 11px system-ui,sans-serif;fill:#4a7a00}.ownership-external{font:700 11px system-ui,sans-serif;fill:#6b7280}
  .edge{fill:none;stroke:#3979ad;stroke-width:2.4;opacity:.82;marker-end:url(#arrow)}.edge.sensitive{stroke:#c45a18;stroke-width:3}.edge.conditional{stroke-dasharray:8 6}
  .trunk{fill:none;stroke:#3979ad;stroke-width:3;opacity:.82}.trunk.neutral{stroke:#6b7280}
  .edge-id{font:700 11px ui-monospace,monospace;fill:#fff}.edge-badge{fill:#3979ad;stroke:#fff;stroke-width:2}.edge-badge.sensitive{fill:#c45a18}
  .legend-title{font:700 19px system-ui,sans-serif;fill:#111827}.legend-text{font:12px system-ui,sans-serif;fill:#374151}.legend-id{font:700 12px ui-monospace,monospace;fill:#111827}
  .scope-box{fill:#fff8e8;stroke:#9a6700;stroke-width:2;rx:12}.scope-title{font:700 15px system-ui,sans-serif;fill:#6b4b00}.scope-text{font:13px system-ui,sans-serif;fill:#4b3a0a}
  .note{font:12px system-ui,sans-serif;fill:#4b5563}.rail{fill:#76b900}
</style>""",
        f'<rect class="bg" width="{width}" height="{height}"/>',
        '<rect class="rail" x="0" y="0" width="1600" height="10"/>',
        f'<text class="title" x="48" y="48">{esc(COURSE_SCOPED_TITLE)}</text>',
        '<text class="subtitle" x="48" y="70">Course-owned nodes are solid green. External dependencies are dashed gray; their live controls are not attested here.</text>',
    ]

    for zone in model["zones"]:
        lines.append(f'<rect class="zone {esc(zone["class"])}" x="{zone["x"]}" y="{zone["y"]}" width="{zone["width"]}" height="{zone["height"]}"/>')
        lines.append(f'<text class="zone-label" x="{zone["x"] + 18}" y="{zone["y"] + 27}">{esc(zone["label"])}</text>')

    for trunk in model.get("layout", {}).get("shared_trunks", []):
        points = " ".join(f"{point[0]:g},{point[1]:g}" for point in trunk["points"])
        classes = "trunk neutral" if trunk.get("class") == "neutral" else "trunk"
        lines.append(f'<polyline class="{classes}" points="{points}"><title>{esc(trunk["label"])}</title></polyline>')

    edge_badges: list[str] = []
    for index, edge in enumerate(model["edges"], 1):
        source, target = nodes[edge["from"]], nodes[edge["to"]]
        points, mx, my = edge_path(source, target, edge.get("route"))
        classes = ["edge"]
        if edge.get("sensitive"):
            classes.append("sensitive")
        if edge.get("conditional"):
            classes.append("conditional")
        summary = f'{edge["id"]}: {edge["protocol"]}; {edge["data"]}; auth: {edge["auth"]}; boundary: {edge["trust_boundary"]}'
        lines.append(f'<polyline class="{" ".join(classes)}" points="{points}"><title>{esc(summary)}</title></polyline>')
        badge_class = "edge-badge sensitive" if edge.get("sensitive") else "edge-badge"
        edge_badges.append(f'<circle class="{badge_class}" cx="{mx:g}" cy="{my:g}" r="13"><title>{esc(summary)}</title></circle>')
        edge_badges.append(f'<text class="edge-id" x="{mx:g}" y="{my + 4:g}" text-anchor="middle">{index}</text>')

    lines.extend(edge_badges)

    for node in model["nodes"]:
        classes = ["node"]
        ownership = node.get("ownership")
        classes.append("toe" if ownership == "toe" else "external-context")
        if node.get("privileged"):
            classes.append("privileged")
        if node.get("conditional"):
            classes.append("conditional")
        x, y, w, h = node["x"], node["y"], node["width"], node["height"]
        title = f'{node["label"]}. Ownership: {ownership}. Assurance: {node.get("assurance", "unknown")}. {node["detail"]}'
        lines.append(f'<rect class="{" ".join(classes)}" x="{x}" y="{y}" width="{w}" height="{h}"><title>{esc(title)}</title></rect>')
        ownership_label = "COURSE-OWNED" if ownership == "toe" else "EXTERNAL DEPENDENCY"
        ownership_class = "ownership-toe" if ownership == "toe" else "ownership-external"
        ownership_anchor = "start" if node.get("ownership_align") == "left" else "end"
        ownership_x = x if ownership_anchor == "start" else x + w
        ownership_y = y + h + 18 if node.get("ownership_position") == "bottom" else y - 8
        if ownership == "external" and node.get("ownership_position") != "bottom":
            lines.append(text_block(
                ownership_x,
                ownership_y - 13,
                [ownership_label, "LIVE CONTROLS NOT ATTESTED"],
                ownership_class,
                anchor=ownership_anchor,
                step=13,
            ))
        else:
            lines.append(f'<text class="{ownership_class}" x="{ownership_x}" y="{ownership_y}" text-anchor="{ownership_anchor}">{esc(ownership_label)}</text>')
        if node.get("privileged"):
            lines.append(f'<rect x="{x}" y="{y}" width="7" height="{h}" rx="4" fill="#c45a18"/>')
        if node.get("conditional"):
            lines.append(f'<text class="note" x="{x + w}" y="{y - 8}" text-anchor="end">conditional</text>')
        label_lines = wrap(node["label"], max(16, int(w / 10)))[:2]
        detail_lines = wrap(node["detail"], max(22, int(w / 8)))[:2]
        label_y = y + 35 if len(label_lines) == 1 else y + 28
        lines.append(text_block(x + w / 2, label_y, label_lines, "node-label", step=18))
        detail_y = y + h - 28 if len(detail_lines) == 1 else y + h - 42
        lines.append(text_block(x + w / 2, detail_y, detail_lines, "node-detail", step=16))

    zone_bottom = max(zone["y"] + zone["height"] for zone in model["zones"])
    scope_y = zone_bottom + 24
    threat_enumeration = model["system"]["threat_enumeration"]
    lines.extend([
        f'<rect class="scope-box" x="48" y="{scope_y}" width="1504" height="110"/>',
        f'<text class="scope-title" x="68" y="{scope_y + 25}">THREAT ENUMERATION BOUNDARY · DECLARED FLOWS ONLY</text>',
        text_block(68, scope_y + 49, wrap(threat_enumeration["rule"], 176)[:2], "scope-text", anchor="start", step=16),
        text_block(68, scope_y + 81, wrap(threat_enumeration["route_consolidation"], 176)[:2], "scope-text", anchor="start", step=16),
    ])
    legend_y = scope_y + 140
    lines.extend([
        f'<text class="legend-title" x="48" y="{legend_y}">Flow register</text>',
        f'<line x1="48" y1="{legend_y + 14}" x2="1552" y2="{legend_y + 14}" stroke="#d1d5db"/>',
    ])
    columns = 2
    per_column = (len(model["edges"]) + columns - 1) // columns
    col_width = 750
    row_height = 88
    for index, edge in enumerate(model["edges"], 1):
        column = (index - 1) // per_column
        row = (index - 1) % per_column
        x = 50 + column * col_width
        y = legend_y + 42 + row * row_height
        label = f'{nodes[edge["from"]]["label"]} → {nodes[edge["to"]]["label"]}'
        if edge.get("conditional"):
            label += " (conditional)"
        objectives = " · ".join(value.title() for value in edge["security_objectives"])
        transport = f'objectives: {objectives} · via {edge["protocol"]} · data: {edge["data"]}'
        control = f'auth: {edge["auth"]} · boundary: {edge["trust_boundary"]}'
        label_lines = wrap(label, 82)[:2]
        transport_lines = wrap(transport, 94)[:2]
        control_lines = wrap(control, 94)[:2]
        label_y = y
        transport_y = label_y + 16 * len(label_lines)
        control_y = transport_y + 16 * len(transport_lines)
        lines.append(f'<text class="legend-id" x="{x}" y="{y}">{index:02d}</text>')
        lines.append(text_block(x + 28, label_y, label_lines, "legend-text", anchor="start", step=16))
        lines.append(text_block(x + 28, transport_y, transport_lines, "note", anchor="start", step=16))
        lines.append(text_block(x + 28, control_y, control_lines, "note", anchor="start", step=16))

    lines.extend([
        f'<line x1="48" y1="{height - 30}" x2="1552" y2="{height - 30}" stroke="#d1d5db"/>',
        f'<text class="note" x="48" y="{height - 10}">Only numbered flows and listed objectives are enumerated · external operator internals are excluded · model fingerprint: {digest[:16]} · design: docs/security-design.md</text>',
        "</svg>",
        "",
    ])
    return "\n".join(lines)


def load_model(path: Path = MODEL) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed SVG is stale")
    parser.add_argument("--model", type=Path, default=MODEL)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    expected = render(load_model(args.model))
    if args.check:
        actual = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
        if actual != expected:
            print(f"security architecture SVG stale: run python3 {Path(__file__).relative_to(ROOT)}")
            return 1
        print(f"security architecture SVG current: {args.output.relative_to(ROOT)}")
        return 0
    args.output.write_text(expected, encoding="utf-8")
    print(f"wrote {args.output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
