#!/usr/bin/env python3
# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate reviewable SKILL.html contracts for every source directory that lacks one."""
from __future__ import annotations

import argparse
import html
import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MARKER = "generated by scripts/skills/gen_directory_beacons.py"

SUMMARIES = {
    ".agents": "Repository-local agent capabilities that are portable across supported harnesses.",
    ".agents/skills": "Reusable repository workflows discovered by Codex and compatible agent hosts.",
    ".agents/skills/nemoclaw-contribution": "Exact-head contribution, compaction, review, and delivery workflow for NemoClawDLI.",
    ".agents/skills/nemoclaw-contribution/agents": "Codex skill-list metadata for the NemoClawDLI contribution workflow.",
    ".codex": "Trusted-project Codex settings and the machine-readable contribution continuity contract.",
    ".codex/hooks": "Small credential-free lifecycle hooks that preserve contribution state around session compaction.",
    ".github": "GitHub contribution intake, dependency automation, and protected workflow definitions.",
    ".github/ISSUE_TEMPLATE": "Structured public issue forms for defects, features, course content, runtime behavior, and source licensing.",
    ".github/workflows": "Pinned GitHub Actions workflows for trusted-base contribution scanning, validation, dependency review, Pages, and protected releases. Every added .yml or .yaml workflow is checked for read-only defaults, fork-safe jobs, isolated write authority, and non-persistent checkout credentials. No checkout persists a credential, so a step that contacts a Git remote authenticates from the read-only job token in its own env. An env-only credential never reaches argv or a stored Git configuration. The pull_request_target boundary reads candidate Git objects with base-owned scanner code and never checks out the proposed head. CodeQL applies the repository's source-bound SARIF policy; release readiness separately requires GitHub's host-owned CodeQL check and pull-request alert state.",
    ".gitlab": "Generic GitLab intake and validation source used when reviewed public commits enter the internal integration repository.",
    ".gitlab/issue_templates": "Internal issue templates aligned with the public contribution categories.",
    ".gitlab/merge_request_templates": "Internal merge-request submission contract and review checklist.",
    "docs/assets": "Reviewed visual evidence referenced by repository documentation.",
    "i18n": "Sparse same-branch locale overlays; runtime modules remain shared with canonical English source.",
    "i18n/es": "Spanish locale metadata and reviewed sparse content overlay.",
    "i18n/es/web": "Spanish foyer and browser-surface overrides.",
    "i18n/es/web/nemoclaw": "Spanish learner-page overrides for the NemoClaw DLI course.",
    "i18n/es/web/nemoclaw/assets": "Spanish localized course assets.",
    "i18n/es/web/nemoclaw/assets/figures": "Spanish figure variants checked against the canonical figure contract.",
    "i18n/pt": "Brazilian Portuguese locale metadata and reviewed sparse content overlay.",
    "i18n/pt/web": "Brazilian Portuguese foyer and browser-surface overrides.",
    "i18n/pt/web/nemoclaw": "Brazilian Portuguese learner-page overrides for the NemoClaw DLI course.",
    "i18n/pt/web/nemoclaw/assets": "Brazilian Portuguese localized course assets.",
    "i18n/pt/web/nemoclaw/assets/figures": "Brazilian Portuguese figure variants checked against the canonical figure contract.",
    "scripts/browser-vendor/license-overrides": "Reviewed license texts for browser packages whose installed metadata is incomplete.",
    "scripts/translate/locales": "Locale-specific translation profiles used by the sparse-overlay workflow.",
    "web/nemoclaw/assets/figures": "Canonical course figures governed by the parent image-provenance contract.",
    "web/nemoclaw/mats/glossary_raw": "Versioned source material used to build the searchable course glossary.",
    "web/nemoclaw/mats/glossary_raw/images": "Images retained with the versioned glossary source material.",
    "web/nemoclaw/vendor": "Pinned same-origin browser dependencies, generated metadata, and license evidence.",
    "web/nemoclaw/vendor/licenses": "Exact license texts shipped for pinned browser dependencies.",
    "scripts/ci": "Fixed-vocabulary internal GitLab operations for exact artifact retrieval, secret-isolated live review, language-selective publication planning, and the root-installed devbox publisher.",
    "scripts/cors-proxy/deployable": "History-free, parameterized source for the optional Lambda and CloudFront browser relays. The course does not deploy or operate this stack.",
    "scripts/cors-proxy/deployable/scripts": "Packaging and operator-run smoke checks for the optional relay stack.",
    "scripts/cors-proxy/deployable/src": "Dependency-free Lambda and CloudFront request-routing implementation.",
    "scripts/cors-proxy/deployable/infrastructure": "Generic operator-parameterized infrastructure template for both relay endpoints.",
    "scripts/cors-proxy/deployable/test": "Node unit tests for request filtering, provider binding, redirects, CORS, streaming, and WebSocket routing.",
    "web/shared": "Pinned browser libraries and course-authored interface primitives shared without creating sibling-course dependencies.",
    "web/shared/vendor": "Byte-identical publisher browser assets with version, license, digest, and reviewed-copy evidence.",
    "web/shared/vendor/licenses": "Complete upstream license texts for the shared browser assets.",
}

GUIDANCE = {
    ".gitlab": '''
  <section aria-labelledby="gitlab-boundary"><h2 id="gitlab-boundary">Why this directory is public</h2>
    <p>This directory keeps the generic validation and intake definitions that the import requires. Runner addresses, deployment destinations, credentials, account identifiers, and generated artifacts remain outside the public source.</p>
  </section>''',
    "scripts/ci": '''
  <section aria-labelledby="operator-flow"><h2 id="operator-flow">Operator flow</h2>
    <ol>
      <li><strong>Select evidence:</strong> use an exact branch, full commit SHA, and successful gate job. Live review also selects provider-matched launchables; publication selects languages and immutable or stable delivery.</li>
      <li><strong>Acquire without candidate execution:</strong> the protected child job verifies GitLab metadata and emits only the bounded archive and request record.</li>
      <li><strong>Exercise or publish:</strong> a separate secret-free job builds the pinned browser runtime without opening candidate content. Candidate browsers run without protected variables. Live probes receive only environment-scoped file secrets. CDN preparation has no AWS authority; the root-installed devbox publisher accepts only its hash plan.</li>
    </ol>
    <p><a href="../../docs/pages_deploy.md">Open the exact <code>glab</code> branch/language commands and runner provisioning steps.</a></p>
    <p>GitLab contains these operations. Public GitHub receives the source and ordinary validation. It receives none of the internal triggers, secrets, protected environments, devbox-runner access, or AWS authority.</p>
  </section>''',
    "scripts/cors-proxy/deployable": '''
  <section aria-labelledby="projection-flow"><h2 id="projection-flow">Verify before use</h2>
    <ol>
      <li><strong>Review provenance:</strong> <a href="PROJECTION.json">PROJECTION.json</a> binds every projected file to its source revision and SHA-256.</li>
      <li><strong>Run source checks:</strong> <code>python3 scripts/security/audit_cors_proxy_projection.py</code> and <code>node --test scripts/cors-proxy/deployable/test/*.test.mjs</code>.</li>
      <li><strong>Supply your environment:</strong> copy the backend and variable examples locally. Never commit state, account, DNS, certificate, credential, or deployed endpoint values.</li>
      <li><strong>Test an approved deployment:</strong> use the smoke scripts with URLs produced by that deployment. The repository does not carry deployment authority.</li>
    </ol>
    <p><a href="README.md">Open the deployment, test, and security-boundary instructions.</a></p>
  </section>''',
}


def source_files() -> list[Path]:
    raw = subprocess.check_output(
        ["git", "-C", str(ROOT), "ls-files", "--cached", "--others", "--exclude-standard", "-z"]
    )
    files = (Path(os.fsdecode(item)) for item in raw.split(b"\0") if item)
    return sorted(path for path in files if (ROOT / path).is_file())


def source_directories(files: list[Path]) -> list[Path]:
    directories = {Path(".")}
    for path in files:
        parent = path.parent
        while parent != Path("."):
            directories.add(parent)
            parent = parent.parent
    return sorted(directories, key=lambda path: (len(path.parts), str(path)))


def role(path: Path) -> str:
    name = path.name
    if name == "SKILL.md":
        return "runtime skill contract"
    if name in {"Containerfile", "Dockerfile"} or name.endswith(".Dockerfile"):
        return "container definition"
    return {
        ".html": "HTML source",
        ".js": "JavaScript source",
        ".mjs": "JavaScript module",
        ".py": "Python source",
        ".sh": "shell source",
        ".md": "documentation",
        ".json": "structured data",
        ".yaml": "YAML configuration",
        ".yml": "YAML configuration",
        ".svg": "SVG asset",
        ".png": "PNG asset",
        ".jpeg": "image asset",
        ".jpg": "image asset",
        ".txt": "text evidence",
        ".css": "stylesheet",
    }.get(path.suffix.lower(), "source artifact")


def title_for(rel: Path) -> str:
    return "repository root" if rel == Path(".") else str(rel)


def summary_for(rel: Path) -> str:
    key = str(rel)
    return SUMMARIES.get(key, f"Source contract for {key}/ and its directly governed files.")


def page(rel: Path, files: list[Path], directories: list[Path]) -> str:
    absolute = ROOT if rel == Path(".") else ROOT / rel
    direct_files = sorted(
        path.name for path in files if path.parent == rel and path.name != "SKILL.html"
    )
    child_dirs = sorted(
        child for child in directories if child.parent == rel and child != rel
    )
    title = title_for(rel)
    summary = summary_for(rel)
    guidance = "\n" + GUIDANCE[str(rel)] if str(rel) in GUIDANCE else ""
    explorer_rel = os.path.relpath(ROOT / "web" / "_skill_explorer.js", absolute)
    home_rel = os.path.relpath(ROOT / "web" / "index.html", absolute)
    map_rel = os.path.relpath(ROOT / "SKILL.html", absolute)
    parent_skill = "SKILL.html" if rel == Path(".") else os.path.relpath(
        (ROOT if rel.parent == Path(".") else ROOT / rel.parent) / "SKILL.html", absolute
    )
    source_dir = "" if rel == Path(".") else str(rel) + "/"
    file_rows = [
        {"path": name, "role": role(Path(name)), "desc": f"{role(Path(name)).capitalize()} in {title}/."}
        for name in direct_files
    ]
    child_rows = [
        {"label": child.name, "href": f"{child.name}/SKILL.html"}
        for child in child_dirs
    ]
    meta = {
        "schema": "dir-skill/1.0",
        "node_type": "directory-explorer",
        "title": title,
        "source_dir": source_dir,
        "summary": summary,
        "explorer": explorer_rel,
    }
    config: dict[str, object] = {
        "title": title,
        "summary": summary,
        "ties": ["build"],
        "nav": {
            "home": home_rel,
            "up": {"label": "parent", "href": parent_skill},
        },
    }
    binary_names = {
        name for name in direct_files
        if Path(name).suffix.lower() in {".ico", ".jpeg", ".jpg", ".png", ".pptx", ".pdf", ".zip"}
    }
    if file_rows and not binary_names:
        config["files"] = file_rows
        if child_rows:
            config["related"] = child_rows
    else:
        config["mode"] = "hub"
        groups = []
        if file_rows:
            groups.append({
                "title": "Files",
                "items": [
                    {"label": row["path"], "href": row["path"], "desc": row["desc"]}
                    for row in file_rows
                ],
            })
        if child_rows:
            groups.append({"title": "Child directories", "items": child_rows})
        config["links"] = groups

    file_links = "\n".join(
        f'      <li><a href="{html.escape(name)}"><code>{html.escape(name)}</code></a></li>'
        for name in direct_files
    ) or "      <li>This directory has no direct files. Open a child contract below.</li>"
    child_links = "\n".join(
        f'      <li><a href="{html.escape(child.name)}/SKILL.html"><code>{html.escape(child.name)}/</code></a></li>'
        for child in child_dirs
    ) or "      <li>No child directories.</li>"
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<!-- {MARKER}; update the summary map or generator, then regenerate -->
<title>{html.escape(title)} directory contract</title>
<script type="application/json" id="skill-meta">
{json.dumps(meta, indent=2)}
</script>
<script type="application/json" id="explorer-config">
{json.dumps(config, indent=2)}
</script>
<style data-skill-static="1">
.skill-static{{padding:24px clamp(18px,4vw,44px);border-bottom:1px solid #2a2a2a;background:#0d0d0d;color:#f2f2f2;font:15px/1.55 system-ui,sans-serif}}
.skill-static a{{color:#76b900}}.skill-static h1{{color:#76b900}}.skill-static code{{font-family:ui-monospace,Consolas,monospace}}
.skill-columns{{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:18px}}.skill-columns ul{{padding-left:1.2rem}}
</style>
</head>
<body>
<section class="skill-static" aria-labelledby="skill-title">
  <header data-skill-header="1">
  <nav aria-label="Skill navigation"><a href="{html.escape(home_rel)}">Course home</a> · <a href="{html.escape(parent_skill)}">Parent contract</a> · <a data-skill-nav="map" href="{html.escape(map_rel)}">Repository map</a></nav>
  </header>
  <h1 id="skill-title">{html.escape(title)}</h1>
  <p>{html.escape(summary)}</p>{guidance}
  <div class="skill-columns">
    <section><h2>Files</h2><ul>
{file_links}
    </ul></section>
    <section><h2>Child directories</h2><ul>
{child_links}
    </ul></section>
  </div>
</section>
<div id="explorer"></div>
<noscript><section class="skill-static"><p>The directory index above remains usable without JavaScript.</p></section></noscript>
<script src="{html.escape(explorer_rel)}"></script>
</body>
</html>
'''


def generate(check: bool) -> int:
    files = source_files()
    directories = source_directories(files)
    changed: list[Path] = []
    for rel in directories:
        target = (ROOT if rel == Path(".") else ROOT / rel) / "SKILL.html"
        if target.exists() and MARKER not in target.read_text(encoding="utf-8", errors="replace"):
            continue
        rendered = page(rel, files, directories)
        if not target.exists() or target.read_text(encoding="utf-8") != rendered:
            changed.append(target)
            if not check:
                target.write_text(rendered, encoding="utf-8")
    if changed:
        action = "would update" if check else "updated"
        for path in changed:
            print(f"{action} {path.relative_to(ROOT)}")
        return 1 if check else 0
    print(f"directory beacons current: {len(directories)} directories")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated beacons are missing or stale")
    args = parser.parse_args()
    return generate(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
