// Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Simplified Chinese glossary localization. Term identities, tags, URLs, tiers, and kinds
// stay canonical; only the learner-facing blurb is localized.
const ZH_BLURBS = Object.freeze({
  "3D Reconstruction": "了解什么是 3D 重建，以及神经重建的工作原理。",
  "AI Agents": "AI 智能体是高级 AI 系统，能够在具备控制措施的安全环境中，根据高层目标自主推理、规划并执行复杂任务。",
  "AI Factory": "AI 工厂是为整个 AI 生命周期设计的专用计算基础设施。",
  "AI Grid": "了解 AI 网格如何跨区域分布 AI 基础设施，在安全高效地路由工作负载的同时平衡性能、成本和延迟。",
  "AI Inference": "AI 推理将机器学习和人工智能技术应用于现实场景，有助于解决高级应用的部署难题。",
  "AI Infrastructure": "AI 基础设施旨在支持 AI 模型和应用的开发、部署与管理。",
  "AI Reasoning": "AI 推理是 AI 系统通过评估不同结果并选择最佳方案来分析和解决问题的过程，类似于人类决策。",
  "AI Training": "AI 训练是教模型从数据中学习模式的过程，使其能够在显式编程之外进行推理、解决问题和生成内容。",
  "AI-RAN": "全面了解 AI 无线接入网络 (AI-RAN)，以及它如何利用 AI 推动 6G 移动网络变革。",
  "AlphaFold2": "AlphaFold2 是 Google DeepMind 于 2020 年开发的机器学习模型，可根据氨基酸序列准确预测蛋白质的三维结构。",
  "Apache MXNet": "机器学习是人工智能 (AI) 的一个子领域，利用算法或统计模型在没有显式编程或人工干预的情况下自动从经验中学习。",
  "Apache Spark": "Apache Spark 是一个开源框架，用于在计算机集群上并行处理大数据任务。",
  "Automatic Speech Recognition (ASR)": "自动语音识别 (ASR) 结合多种处理流程和软件，对人类语音进行解码并将其转换为数字文本。",
  "Autonomous Networks": "由 AI 驱动的系统会分析遥测数据、预测问题、在数字孪生中模拟变更，并在尽量减少人工干预的情况下持续优化多供应商网络运营。",
  "Autonomous Vehicles": "Robotaxi 是完全无人驾驶的按需出行自动驾驶车辆，以 SAE L4 级自动驾驶运行，无须人类驾驶员即可安全运送乘客或货物。",
  "BERT": "BERT (Bidirectional Encoder Representations from Transformers) 是 Google 开发的深度学习模型，用于 NLP 预训练和微调。",
  "Chain of Thought Prompting": "思维链 (CoT) 是一种提示词工程技术，可帮助大型语言模型 (LLM) 更准确地推理。",
  "Cluster Analysis / Clustering": "聚类分析根据对象特征对其分组，使同一簇内的相似度较高、不同簇之间的相似度较低。",
  "Computer Vision": "计算机视觉是 AI 和深度学习的一个子领域，通过训练卷积神经网络获得类似人类的视觉能力并用于各类应用。",
  "Convolutional Neural Network": "卷积神经网络 (CNN) 是一种深度学习网络，主要用于识别和分类图像以及检测图像中的对象。它特别适合映射图像数据，并具有较高的计算效率。",
  "Dask": "Dask 是一个用于 Python 并行和分布式计算的灵活开源库。",
  "Data Flywheel": "数据飞轮是一种反馈循环：利用交互或流程中收集的数据持续改进 AI 模型，改进后的模型又会产生更好的结果和更有价值的数据。",
  "Deep Agents": "深度智能体是面向复杂长期任务的 AI 智能体。了解显式规划、持久记忆和子智能体委派如何支撑自主工作流。",
  "Deep Learning": "深度学习是一种机器学习方法，也是人工智能 (AI) 的一个子领域。它利用人工神经网络识别数据中的模式，其工作方式类似于人脑。",
  "Digital Twin": "数字孪生是产品、流程和设施的虚拟表示，企业可使用它来设计、模拟和运营对应的物理实体。",
  "Embodied AI": "具身 AI 是指将人工智能集成到物理系统中，使其能够与现实世界互动。",
  "Energy Efficiency": "能源效率是指系统或设备在可接受范围内完成特定任务或功能时尽可能减少能源消耗的能力。",
  "Frontier Models": "前沿 AI 模型是最先进的通用模型，可通过优化性能支持推理、多模态生成和智能体工作流。",
  "Generative AI": "生成式 AI 让用户能够根据多种输入快速生成新内容。了解其优势、应用和挑战等内容。",
  "Graph Analytics": "图分析是一套 Python 工具，用于创建和处理复杂网络，并研究其结构、动态与功能。",
  "High-Performance Computing": "高性能计算 (HPC) 系统具有高速处理能力、高性能网络和大容量内存。",
  "Humanoid Robot": "人形机器人是仿照人体形态设计的通用双足机器人，可与人类协作以提高生产力。",
  "Imitation Learning": "模仿学习是一种机器学习方法，智能体通过观察并模仿专家示范来学习执行任务或掌握新技能。",
  "Industrial AI": "工业 AI 是工业自动化的重要推动力，可增强机器、系统和流程在尽量减少人工干预的情况下运行的能力。",
  "K-Means Clustering Algorithm": "K-means 是一种聚类算法，也是数据科学家最常用且最简单的无监督机器学习 (ML) 算法之一。",
  "Kubernetes": "Kubernetes 是一个开源编排平台，用于管理封装在软件容器中的工作负载和服务。",
  "Large Language Models": "大型语言模型 (LLM) 是深度学习算法，可利用超大规模数据集识别、总结、翻译、预测和生成内容。",
  "Machine Learning": "机器学习是人工智能 (AI) 的一个子领域，利用算法或统计模型在没有显式编程或人工干预的情况下自动从经验中学习。",
  "Machine Learning Operations (MLOps)": "MLOps 是一组实践和原则，旨在简化生产环境中机器学习 (ML) 模型的开发、部署和维护。",
  "Mixed Integer Programming": "混合整数规划 (MIP) 是运筹学和决策科学中广泛使用的强大工具，用于解决复杂的优化问题。",
  "Mixture-of-Transformers": "了解 Mixture of Transformers (MoT) 架构。这是一种高效多模态 AI 的统一系统，通过条件计算支持可扩展的基础模型。",
  "Multi-Agent Systems": "多智能体系统由多个专用 AI 智能体组成，它们协同解决复杂问题，也称为智能体团队。",
  "Natural Language Processing": "自然语言处理 (NLP) 利用计算机和软件理解人类语言的含义。",
  "NetworkX": "NetworkX 是一个 Python 软件包，用于创建和处理复杂网络，并研究其结构、动态与功能。",
  "Numba": "Numba 是一个开源的 Python 即时编译器，开发者可以使用标准 Python 函数加速 CPU 和 GPU 上的数值计算。",
  "NumPy": "NumPy 是一个免费开源的 Python 库，用于处理 N 维数组和执行数值计算。",
  "Omni-Model": "了解全模态模型（多模态 AI）的定义，以及 NVIDIA Cosmos 和 Nemotron 等平台如何在智能体 AI 和物理 AI 应用中为其提供支持。",
  "pandas": "pandas 是一个基于 Python 构建的开源软件库，用于数据分析和数据处理。",
  "Physical AI": "物理 AI 使自主机器能够感知、理解现实（物理）世界并执行复杂操作。",
  "Polars": "Polars 是一个用于数据处理和分析的开源 DataFrame 库。它使用 Rust 实现，并采用 Apache Arrow 的列式内存格式来高效处理数据。",
  "Power Efficiency": "功耗效率是指单位电能所能完成的计算工作和数据移动量达到最大。",
  "Product Configurator": "产品配置器是一种可视化工具，允许用户实时定制产品。",
  "PyTorch": "PyTorch 是一个功能完善的框架，用于构建深度学习模型；深度学习属于机器学习。",
  "Quantum Computing": "量子计算是一项范式变革技术，利用量子物理定律解决极其困难的问题。",
  "Random Forest": "随机森林（又称随机决策森林）是一种监督分类算法，其学习方法由多棵决策树组成，输出是对问题最佳答案的共识。",
  "Reasoning Vision Language Action": "推理型 VLA（视觉-语言-动作）是一种统一的人工智能模型，将视觉感知、语言理解和动作生成与逐步推理结合起来。",
  "Recommendation System": "推荐系统是一种人工智能算法，通常与机器学习相关。",
  "Regression": "线性回归和逻辑回归用于确定一个或多个自变量如何影响因变量。",
  "Reinforcement Learning": "强化学习 (RL) 是一种机器学习技术，使机器人能够通过经验学习并作出智能决策。",
  "Retrieval-Augmented Generation (RAG)": "RAG 使用相关数据增强大型语言模型的提示词，从而生成更实用、更准确的回答。了解其架构及更多内容。",
  "Robot Learning": "机器人学习是一组算法和方法，可帮助机器人学习操作、移动等新技能。",
  "Scikit-learn": "scikit-learn 是 Python 生态系统中广泛使用的开源库，专门用于机器学习相关任务。",
  "Sensor Simulation": "传感器仿真复制现实世界中的传感器行为，从而为机器人、汽车和工业应用提供安全的 AI 训练、测试与验证环境。",
  "Sentiment Analysis": "情感分析是对书面评论和社交媒体帖子等文本数据中的情绪进行自动解释和分类。",
  "SimReady": "SimReady（即“simulation-ready”）是一项面向物理精确 3D 资产的标准；此类资产包含真实世界的属性、行为和数据绑定（例如 IoT）。",
  "Small-Molecule Hit Identification": "苗头化合物识别也称为苗头发现，是寻找可能与特定生物靶点结合的小型类药分子的过程。",
  "Spatial Computing": "空间计算实时融合数字数据与物理世界，通过 AR/VR 头显或智能眼镜等设备增强混合现实交互。",
  "Specialized AI": "了解专用 AI、它所服务的行业、使用的模型类型及其工作原理。",
  "Speech AI": "语音 AI 是对话式 AI 的一个子领域，包括将口语转换为文本的自动语音识别 (ASR) 和文本转语音 (TTS)。",
  "Stream Processing": "流处理是指在收到新数据事件时持续对其进行处理。",
  "Synthetic Data": "合成数据是通过计算机仿真、生成式 AI 模型或二者结合，在可见光和非可见光谱中生成文本、二维图像或三维图像的过程。",
  "TensorFlow": "TensorFlow 是全球最受欢迎的开源库，用于开发和部署先进的机器学习算法。",
  "Text-to-Speech": "文本转语音是一种语音合成形式，可将任意文本字符串转换为语音输出。",
  "Vector Database": "向量数据库是经过组织的向量嵌入集合，可以随时创建、读取、更新和删除其中的数据。",
  "Virtual Screening": "虚拟筛选是一种药物发现计算技术，用于评估大规模小分子或化合物库并找出潜在候选药物。",
  "Vision Language Models": "视觉语言模型 (VLM) 是多模态生成式 AI 模型，能够基于文本、图像和视频提示词进行推理。",
  "World Action Model": "世界动作模型 (WAM) 是一种机器人 AI 模型，利用视频预训练联合预测未来世界状态和机器人动作。了解 WAM 如何支持零样本泛化、跨本体迁移和实时控制。",
  "World Foundation Models": "世界模型是理解现实世界动态（包括物理规律和空间属性）的神经网络。",
  "XGBoost": "XGBoost 是一个开源软件库，实现了梯度提升框架下的机器学习算法。它日益流行，被全球许多数据科学家用于解决回归、分类、排序和自定义预测问题。",
  "Deploy Self-Evolving Agents for Faster, More Secure Research with a Hermes Agent and NVIDIA NemoClaw | NVIDIA Technical Blog": "AI 智能体可以综合数据，从而加快研究、总结信息并帮助团队更快地作出决策。",
  "From Local to Global: A Graph RAG Approach to Query-Focused Summarization": "检索增强生成 (RAG) 从外部知识源获取相关信息，使大型语言模型 (LLM) 能够回答与私有数据和既有知识相关的问题……",
  "ReAct: Synergizing Reasoning and Acting in Language Models": "大型语言模型 (LLM) 在语言理解和交互式决策等任务中展现出强大能力，但其推理能力（例如思维链）……",
  "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks": "大型预训练语言模型能够在参数中存储事实知识，并在针对下游 NLP 任务进行微调后取得先进成果，但其能力仍然……",
  "ReWOO: Decoupling Reasoning from Observations for Efficient Augmented Language Models": "增强语言模型 (ALM) 将大型语言模型 (LLM) 的推理能力与知识检索和动作执行工具相结合。现有 ALM 系统会触发 LLM……"
});

export function localizeGlossaryEntry(entry) {
  if (!document.documentElement.lang.toLowerCase().startsWith("zh")) return entry;
  const blurb = ZH_BLURBS[String(entry?.term || "")];
  return blurb ? { ...entry, blurb } : entry;
}

export function localizeGlossaryEntries(entries) {
  return Array.isArray(entries) ? entries.map(localizeGlossaryEntry) : [];
}
